version: "2.3"
services:
  cern-search-api:
    build:
      context: .
      args:
        build_env: ${ENV}
    container_name: ${CONTAINER_NAME}
    volumes:
      - files:/usr/share/cern-search-api/files
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
    networks:
      - default
    env_file:
      - .env
    user: root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - default
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - default

  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
    networks:
      - default

  postgres:
    image: centos/postgresql-95-centos7
    environment:
      - POSTGRESQL_USER
      - POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE
    volumes:
      - pgsql-data:/var/lib/pgsql/data
    networks:
      - default
    ports:
      - 5432:5432

  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - "8080:8080"
    depends_on:
      - cern-search-api
    volumes:
      - ./nginx/tls:/etc/nginx/tls
      - nginx-cache:/var/cache/nginx
      - nginx-run:/var/run
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  default:

volumes:
  es-data:
  pgsql-data:
  nginx-run:
  nginx-cache:
  nginx-tls:
  files:
