version: "2.3"
services:
  cern-search-api:
    build:
      context: .
      args:
        build_env: ${ENV}
    image: cern-search-rest-api
    container_name: ${CONTAINER_NAME}
    volumes:
      - files:/usr/share/cern-search-api/files
    ports:
      - "5000:5000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - default
    env_file:
      - .env
    user: root

  worker:
    image: cern-search-rest-api
    volumes:
      - files:/usr/share/cern-search-api/files
    depends_on:
      cern-search-api:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - default
    env_file:
      - .env
    command: [
      "/bin/bash",
      "-c",
      "celery worker -A ${WORKER_APP} --loglevel=${CELERY_LOG_LEVEL} --autoscale=1000,500 --without-gossip --without-mingle --pool=gevent"
    ]
    healthcheck:
      test: ["CMD", "celery inspect ping -A ${WORKER_APP} -d celery@$$(hostname)"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - default
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 5601:5601
    networks:
      - default

  redis:
    image: redis:5.0.6
    ports:
      - 6379:6379
    networks:
      - default

  postgres:
    image: centos/postgresql-95-centos7
    environment:
      - POSTGRESQL_USER
      - POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE
    volumes:
      - pgsql-data:/var/lib/pgsql/data
    networks:
      - default
    ports:
      - 5432:5432

  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - "8080:8080"
    depends_on:
      - cern-search-api
    volumes:
      - ./nginx/tls:/etc/nginx/tls
      - nginx-cache:/var/cache/nginx
      - nginx-run:/var/run
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    image: rabbitmq:3.8.2-management
    env_file:
      - .env
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s

  flower:
    image: mher/flower
    env_file:
      - .env
    command: [
      "--broker=amqp://guest:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672",
      "--broker_api=http://guest:${RABBITMQ_DEFAULT_PASS}@rabbitmq:15672/api",
      "--basic_auth=admin:${FLOWER_PASS}"
    ]
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - default

  tika:
    image: logicalspark/docker-tikaserver:1.23
    ports:
      - "9998:9998"
    networks:
      - default

networks:
  default:

volumes:
  es-data:
  pgsql-data:
  nginx-run:
  nginx-cache:
  nginx-tls:
  files:
